### ISSUE TITLE
HTLoading(this).dismiss() 关闭不了

### ISSUE THREAD

**Issue by liangfengyuan** [lhtdeg/AndroidLoadingDialog#2]
HTLoading(this).dismiss()  关闭不掉loading页 
在kotlin中使用的

**Comment by liangfengyuan** [comment]
我的应用是双屏的。可能和这个有关。

**Comment by HartleyLau** [comment]
抱歉，这个库是5年前写的，可能很多方法已经被废弃，构建版本也较老，不建议您继续在此基础上进行开发。
您可以参考一下 https://github.com/li-xiaojun/XPopup 这个项目，该项目的弹窗功能理论上应该可以满足您的要求
